substitutions:
  tx_pin: GPIO16
  rx_pin: GPIO17
  tx_enable_pin: GPIO4

esphome:
  name: trane-rs485-test
  friendly_name: Trane RS485 Test

esp32:
  variant: esp32c6
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:

ota:
  platform: esphome

wifi:
  ssid: "Gipsy Danger"
  password: !secret wifi_password

uart:
  id: uart_bus
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  baud_rate: 9600

external_components:
  - source:
      type: local
      path: components

trane_uart:
  uart_id: uart_bus
  tx_enable_pin: ${tx_enable_pin}
