esphome:
  name: trane-canbus-test
  friendly_name: Trane CANBus Test

esp32:
  variant: esp32c6
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:
ota:
  platform: esphome

wifi:
  ssid: "Gipsy Danger"
  password: !secret wifi_password

canbus:
  - platform: esp32_can
    tx_pin: GPIO5
    rx_pin: GPIO4
    can_id: 0x10
    bit_rate: 250kbps
    on_frame:
      - can_id: 0x000      # Match from ID 0
        can_id_mask: 0x000 # Mask 0 = match everything
        then:
          - lambda: |-
              uint32_t now = millis();
              ESP_LOGI("CAN", "[%lu ms] RX Frame: LEN=%d",
                        (unsigned long) now, x.size());
              for (size_t i = 0; i < x.size(); i++) {
                ESP_LOGI("CAN", "  Data[%u] = 0x%02X", (unsigned) i, x[i]);
              }
